// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251116093356_UpdateModels")]
    partial class UpdateModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("GameMode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdventure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCreative")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSpectator")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSurvival")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameModes");
                });

            modelBuilder.Entity("Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedModes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BaseValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVehicle")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxStackSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Monster", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardItemId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RewardQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RewardXp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RewardItemId");

                    b.ToTable("Monsters");
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentModeId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Hunger")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Realm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CurrentModeId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PlayerInventory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SlotIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ResourceId");

                    b.ToTable("PlayerInventory");
                });

            modelBuilder.Entity("PlayerQuest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("QuestId");

                    b.ToTable("PlayerQuests");
                });

            modelBuilder.Entity("Quest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RewardItemId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RewardQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RewardXp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RewardItemId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("Recipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutputQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequiredModeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("RequiredModeId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RecipeIngredient", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("ResourceId");

                    b.ToTable("RecipeIngredient");
                });

            modelBuilder.Entity("Resource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Shop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedModes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVehicle")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PriceXp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Shop");
                });

            modelBuilder.Entity("WebApplication1.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("WebApplication1.Models.PlayerMonsterKill", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("KilledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MonsterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerMonsterKills");
                });

            modelBuilder.Entity("Monster", b =>
                {
                    b.HasOne("Item", "RewardItem")
                        .WithMany("MonstersRewarding")
                        .HasForeignKey("RewardItemId");

                    b.Navigation("RewardItem");
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.HasOne("WebApplication1.Models.Account", "Account")
                        .WithMany("Players")
                        .HasForeignKey("AccountId");

                    b.HasOne("GameMode", "CurrentMode")
                        .WithMany("Players")
                        .HasForeignKey("CurrentModeId");

                    b.Navigation("Account");

                    b.Navigation("CurrentMode");
                });

            modelBuilder.Entity("PlayerInventory", b =>
                {
                    b.HasOne("Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("Player", "Player")
                        .WithMany("PlayerInventory")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId");

                    b.Navigation("Item");

                    b.Navigation("Player");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("PlayerQuest", b =>
                {
                    b.HasOne("Player", "Player")
                        .WithMany("PlayerQuests")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Quest", "Quest")
                        .WithMany()
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Player");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Quest", b =>
                {
                    b.HasOne("Item", "RewardItem")
                        .WithMany("QuestsRewarding")
                        .HasForeignKey("RewardItemId");

                    b.Navigation("RewardItem");
                });

            modelBuilder.Entity("Recipe", b =>
                {
                    b.HasOne("Item", "Item")
                        .WithMany("RecipesProduced")
                        .HasForeignKey("ItemId");

                    b.HasOne("GameMode", "RequiredMode")
                        .WithMany("Recipes")
                        .HasForeignKey("RequiredModeId");

                    b.Navigation("Item");

                    b.Navigation("RequiredMode");
                });

            modelBuilder.Entity("RecipeIngredient", b =>
                {
                    b.HasOne("Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId");

                    b.HasOne("Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId");

                    b.Navigation("Recipe");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("Shop", b =>
                {
                    b.HasOne("Item", "Item")
                        .WithMany("Shops")
                        .HasForeignKey("ItemId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WebApplication1.Models.PlayerMonsterKill", b =>
                {
                    b.HasOne("Monster", "Monster")
                        .WithMany()
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Player", "Player")
                        .WithMany("MonsterKills")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Monster");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameMode", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("Item", b =>
                {
                    b.Navigation("MonstersRewarding");

                    b.Navigation("QuestsRewarding");

                    b.Navigation("RecipesProduced");

                    b.Navigation("Shops");
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.Navigation("MonsterKills");

                    b.Navigation("PlayerInventory");

                    b.Navigation("PlayerQuests");
                });

            modelBuilder.Entity("Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("WebApplication1.Models.Account", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
